#!/usr/bin/env python3
"""Create temporary linker definitions for address-bearing split labels.

At the initial split there is no curated symbol database. spimdisasm still
uses stable labels such as ``D_8002D4B0`` and ``func_80001050``. Those labels
encode their target address, so a raw-assembly bootstrap can safely define
only otherwise unresolved labels from their names. This file is generated
under ``build/`` and is superseded by real symbols as the project is mapped.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SYMBOL_PATTERN = re.compile(
    r"\b(?P<name>(?:D|func|jtbl)_(?P<address>[0-9A-Fa-f]+)(?:_[A-Za-z0-9]+)?)(?![0-9A-Fa-f])"
)


def collect_symbols(source_directories: list[Path] | Path) -> dict[str, int]:
    """Return label-to-address mappings encoded in bootstrap source names."""

    if isinstance(source_directories, Path):
        source_directories = [source_directories]
    symbols: dict[str, int] = {}
    for directory in source_directories:
        for source in sorted(path for path in directory.rglob("*") if path.is_file()):
            for match in SYMBOL_PATTERN.finditer(source.read_text(encoding="utf-8")):
                symbols[match.group("name")] = int(match.group("address"), 16)
    return symbols


def render(symbols: dict[str, int]) -> str:
    lines = [
        "/* Generated by scripts/create_bootstrap_symbols.py; do not edit. */",
        "/* Address-bearing labels from reference assembly during bootstrap. */",
    ]
    lines.extend(f"PROVIDE({name} = 0x{address:X});" for name, address in sorted(symbols.items()))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source_directories", nargs="+", type=Path)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(render(collect_symbols(arguments.source_directories)), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
