"""ROM character appearance defaults consumed by the ordinary US renderer.

Bank 0x11 is indexed by character ID. This module describes the initializer's
default selection and verified instance presets; it never reads a capture.
"""

from __future__ import annotations

import hashlib
import struct


# Explicit inspection choices among stored expressions, not actor initializer
# defaults. Carl's preset 1 closes Quentin's eyes without changing geometry.
EXPRESSION_PREVIEW_PRESETS = {82: 1}


# Executable consumers, checked against the checksum-validated ROM, not ASM
# generated by the current C build. See docs/evidence/us_rom_character_defaults.md.
US_CONSUMER_WORDS = {
    0x1503D7B8: 0x24080011,  # indexed path bank 0x11
    0x1503D7C0: 0x24070002,  # two path components
    0x1503D7C8: 0x0D40ADAF,  # func_1502B6BC
    0x15083A50: 0x904C003B,  # default header -> actor selector
    0x15083A54: 0xA08C0068,
    0x15083A58: 0x904D003C,
    0x15083A5C: 0xA08D0069,
    0x1502F0D8: 0x916C0008,  # blink lookup begins at header +8
    0x1502F17C: 0x2407000C,  # texture descriptor stride
    0x1502F1F0: 0x928D0068,  # segment 10 selector
    0x1502F214: 0x92880069,  # segment 11 selector
    0x1503DC9C: 0x8E040004,  # descriptor flat ID
    0x1503DCA8: 0x0D44343B,  # func_1510D0EC
    0x1503DCBC: 0xAD420000,  # loaded base -> descriptor pointer
}


def verify_consumers(code: bytes, base: int) -> dict:
    for address, word in US_CONSUMER_WORDS.items():
        offset = address - base
        if offset < 0 or offset + 4 > len(code) or struct.unpack_from('>I', code, offset)[0] != word:
            raise ValueError(f'ROM character-default consumer changed at 0x{address:08X}')
    return {f'0x{address:08X}': f'0x{word:08X}' for address, word in US_CONSUMER_WORDS.items()}


def parse_defaults(data: bytes) -> dict:
    if len(data) < 80 or len(data) % 16:
        raise ValueError('character-default bundle has invalid alignment or length')
    offset, size, expression_offset, expression_flags = struct.unpack_from('>4I', data)
    if (offset, size) != (16, 64) or expression_flags & 0xF0000000 != 0x80000000:
        raise ValueError('character-default bundle descriptor layout changed')
    expression_size = expression_flags & 0x0FFFFFFF
    if expression_offset != (80 if expression_size else 0):
        raise ValueError('character-default expression descriptor is invalid')
    end = 80 + expression_size
    if end > len(data) or len(data) - end >= 16 or any(data[end:]):
        raise ValueError('character-default bundle has invalid expression span or padding')
    header = data[16:80]
    return {
        'sha1': hashlib.sha1(data).hexdigest(),
        'header_sha1': hashlib.sha1(header).hexdigest(),
        'expression_offset': expression_offset,
        'expression_size': expression_size,
        'padding_size': len(data) - end,
        'preset': 'initializer-default-no-expression-blink-zero',
        'descriptor_indices': {'6': header[8], '7': header[11], '10': header[59], '11': header[60]},
    }


def select_descriptor(defaults: dict, descriptors: list[dict], segment: int) -> dict | None:
    index = defaults['descriptor_indices'].get(str(segment))
    if index is None:
        return None
    if not 0 <= index < len(descriptors):
        return None
    descriptor = descriptors[index]
    if descriptor['record_index'] != index or not descriptor['flat_index']:
        return None
    return descriptor


def instance_texture_presets(code: bytes, base: int) -> dict:
    """Prove model 59's post-initializer shirt selection from native code.

    The multiplayer initializer clamps the team index to 0..3, then writes
    index + 1 to actor byte 0x68 for model 0x3B. The multiplayer character
    switch path repeats that assignment. Header selector zero is not a shirt.
    """
    spans = ((0x150830A8, 92, '6fe91bd3f6baebebc9c39947b34abec05214eaad'),
             (0x151E5F64, 72, '1b834e4fee9f6356e1a4dd532bd755bfa98ee275'),
             (0x151E8194, 24, 'fa3015883f323cd01b5214373b18072081e62d9a'))
    for address, size, expected in spans:
        offset = address - base
        if offset < 0 or hashlib.sha1(code[offset:offset + size]).hexdigest() != expected:
            raise ValueError(f'ROM instance texture consumer changed at 0x{address:08X}')

    def immediate(address):
        return struct.unpack_from('>I', code, address - base)[0] & 0xFFFF

    entry = immediate(0x150830DC)
    count = immediate(0x150830C4)
    first = immediate(0x150830E0)
    return {entry: {
        'preset': 'multiplayer-team-index-0-no-expression-blink-zero',
        'segment': 10,
        'actor_selector_offset': f'0x{immediate(0x150830F0):X}',
        'descriptor_indices': list(range(first, first + count)),
        'selected_variant': 0,
        'selection_policy': 'first-of-four-ROM-proven-multiplayer-variants',
        'consumer_sha1': {f'0x{address:08X}': expected for address, _, expected in spans},
    }}


def preview_defaults(manifest: dict, entry: int) -> dict | None:
    """Apply a declared preview preset while retaining the raw header record."""
    initial = manifest['entries'].get(entry)
    if initial is None:
        return None
    renderer = manifest.get('renderer_texture_presets', {}).get(entry)
    if renderer is not None:
        if (entry in manifest.get('instance_texture_presets', {})
                or entry in manifest.get('expression_preview_presets', {})):
            raise ValueError('renderer and other texture presets overlap')
        overrides = renderer['descriptor_indices']
        if (not overrides or set(overrides) - {'6', '7', '10', '11'}
                or any(not isinstance(i, int) or not 0 <= i <= 255 for i in overrides.values())):
            raise ValueError('renderer texture selectors are invalid')
        return {**initial, 'preset': renderer['preset'],
                'descriptor_indices': {**initial['descriptor_indices'], **overrides},
                'renderer_texture_selection': {
                    **renderer, 'initializer_descriptor_indices': initial['descriptor_indices']}}
    expression = manifest.get('expression_preview_presets', {}).get(entry)
    if expression is not None:
        if entry in manifest.get('instance_texture_presets', {}):
            raise ValueError('expression and instance texture presets overlap')
        return expression_preview_defaults(initial, expression)
    preset = manifest.get('instance_texture_presets', {}).get(entry)
    if preset is None:
        return initial
    index = preset['selected_variant']
    choices = preset['descriptor_indices']
    if not isinstance(index, int) or not 0 <= index < len(choices):
        raise ValueError('instance texture variant is outside its verified range')
    segment = str(preset['segment'])
    if segment not in ('10', '11') or any(not isinstance(i, int) or i < 0 for i in choices):
        raise ValueError('invalid instance texture preset')
    return {**initial, 'preset': preset['preset'],
            'descriptor_indices': {**initial['descriptor_indices'], segment: choices[index]},
            'instance_texture_selection': {
                **preset, 'initializer_descriptor_index': initial['descriptor_indices'][segment],
                'selected_descriptor_index': choices[index],
            }}


def expression_preview_defaults(initial: dict, selection: dict) -> dict:
    """Resolve a stored, texture-only expression through its native blink codes."""
    index = selection['index']
    presets = initial.get('expression_presets', [])
    if not isinstance(index, int) or not 0 <= index < len(presets):
        raise ValueError('expression preview is outside its stored range')
    preset = presets[index]
    if (preset['index'] != index or preset['morph_shape'] != 0
            or preset['animation_selector'] != 0 or preset['reserved_byte'] != 0):
        raise ValueError('expression preview requires unsupported morph or action state')
    codes = preset['actor_blink_codes']
    selectors = preset['blink_selector_bytes']
    overrides = preset['texture_descriptor_overrides']
    if (len(codes) != 2 or len(selectors) != 2 or len(overrides) != 2
            or any(not isinstance(v, int) or not 0 <= v <= 245 for v in selectors)
            or codes != [v + 10 for v in selectors]
            or any(not isinstance(v, int) or not 0 <= v <= 255 for v in overrides)):
        raise ValueError('expression preview blink or texture selectors are invalid')
    # func_1507E5C8 writes descriptor+10 to actor bytes 0x6C/0x6D.
    # func_1502F01C subtracts 10 and bypasses the normal blink lookup table.
    resolved = {**initial['descriptor_indices'], '6': codes[0] - 10, '7': codes[1] - 10}
    for segment, override in zip(('10', '11'), overrides):
        if override:
            resolved[segment] = override
    return {**initial, 'preset': f'ROM-stored-expression-{index:04d}-texture-only',
            'descriptor_indices': resolved,
            'expression_texture_selection': {
                'selection_policy': 'explicit-inspection-preset-not-initializer-default',
                'stored_preset': preset,
                'initializer_descriptor_indices': initial['descriptor_indices'],
                'selected_descriptor_indices': resolved,
                'consumer_sha1': selection['consumer_sha1'],
            }}


def expression_texture_consumers(code: bytes, base: int) -> dict:
    """Guard expression application and the direct descriptor blink-code path."""
    spans = ((0x1507E5C8, 240, '77b08fc8d2ec99c73d27527f43df6c9952d0c5fa'),
             (0x1502F09C, 0x128, 'd8f5f30395b69f0c6bcd8cbe1461bb914e4ae070'))
    for address, size, expected in spans:
        offset = address - base
        if offset < 0 or hashlib.sha1(code[offset:offset + size]).hexdigest() != expected:
            raise ValueError(f'ROM expression texture consumer changed at 0x{address:08X}')
    return {f'0x{address:08X}': expected for address, _, expected in spans}


def renderer_texture_presets(code: bytes, base: int) -> dict:
    """Explicit inspection states established by native per-actor updates."""
    spans = ((0x150EE00C, 256, 'b9a32d2f1c61ad06f2d63f3b2dadddbe614b31bd'),
             (0x150F1CB0, 96, '4ceb60c5b35d31cc6e2df4d6a5b06b979ffb86e3'),
             (0x150622F8, 28, 'acb3c86862962cf9c98de7e18d177209c2c0bcb0'))
    for address, size, expected in spans:
        offset = address - base
        if offset < 0 or hashlib.sha1(code[offset:offset + size]).hexdigest() != expected:
            raise ValueError(f'ROM renderer texture consumer changed at 0x{address:08X}')
    offset = 0x15061BD8 - base
    if offset < 0 or code[offset:offset + 4] != bytes.fromhex('92700004'):
        raise ValueError('ROM renderer texture model-ID load changed')
    blink_consumers = expression_texture_consumers(code, base)

    def immediate(address):
        return struct.unpack_from('>I', code, address - base)[0] & 0xFFFF

    # Zero velocity follows the false branches of both +/-5 comparisons.
    # The updater stores direct blink codes: descriptor+10 for segment six,
    # literal 19 (descriptor 9) for segment seven. Entry 119 shares this native
    # handler; its existing initializer preview is kept as a separate choice.
    tank_entry = immediate(0x150EE018)
    tank_codes = [immediate(0x150EE0FC) + immediate(0x150EE100), immediate(0x150EE0F0)]
    # For entry 123, logical animation !=20 selects descriptor 12. With damage
    # flags zero, the helper selects descriptor 19 for segment eleven.
    experiment_entry = immediate(0x150622F8)
    return {
        tank_entry: {'preset': 'ROM-renderer-stationary-tank-inspection',
                     'descriptor_indices': {'6': tank_codes[0] - 10, '7': tank_codes[1] - 10},
                     'actor_blink_codes': tank_codes,
                     'runtime_state': {'actor_0x3C_f32': 0.0, 'actor_0x44_f32': 0.0},
                     'selection_policy': 'explicit-inspection-state-not-initializer-default',
                     'consumer_sha1': {**blink_consumers, '0x150EE00C': spans[0][2]}},
        experiment_entry: {'preset': 'ROM-renderer-undamaged-experiment-inspection',
                          'descriptor_indices': {'10': immediate(0x150F1CC0),
                                                 '11': immediate(0x150F1CD4)},
                          'runtime_state': {'actor_0x84_u16': 0, 'actor_0x2E4_u32': 0},
                          'selection_policy': 'explicit-inspection-state-not-initializer-default',
                          'consumer_sha1': {'0x150F1CB0': spans[1][2], '0x150622F8': spans[2][2]},
                          'model_id_load': {'address': '0x15061BD8', 'word': '0x92700004'}},
    }


def verify_expression_consumers(code: bytes, base: int) -> dict:
    spans = ((0x1507E908, 96, 'c602e20a2b335d94feb349539cbdb76d69957d50'),
             (0x1507E5C8, 240, '77b08fc8d2ec99c73d27527f43df6c9952d0c5fa'),
             (0x1507EA44, 120, 'c4818df6a7fca422de2d463163d68866d05b090f'),
             (0x1507E9F8, 76, '31fcadb16432eb6925dc6fcf17d561857102493d'),
             (0x15083568, 356, '419012702249e321c26fc2badb49949b0aafa0fc'))
    for address, size, sha1 in spans:
        offset = address - base
        if offset < 0 or hashlib.sha1(code[offset:offset + size]).hexdigest() != sha1:
            raise ValueError(f'ROM expression consumer changed at 0x{address:08X}')
    return {f'0x{address:08X}': sha1 for address, _, sha1 in spans}


def parse_expression_animation_programs(data: bytes, base: int) -> list[dict]:
    """Preserve Conker's action programs without calling them animation clips."""
    def span(address, size):
        offset = address - base
        if offset < 0 or offset + size > len(data):
            raise ValueError('expression action program exceeds ROM data')
        return data[offset:offset + size]

    actions = span(0x8009D910, 5)
    if actions != bytes((5, 6, 7, 10, 11)):
        raise ValueError('expression action selector table changed')
    programs = []
    for selector, action in enumerate(actions, 1):
        address = 0x80086CC4 + (action - 1) * 8
        header = span(address, 8)
        pointer, count, reserved = struct.unpack('>IB3s', header)
        if not count or pointer % 4:
            raise ValueError('expression action program has invalid pointer or count')
        raw = span(pointer, count * 16)
        records = [{'index': index, 'dispatch_kind': raw[index * 16 + 3],
                    'raw_bytes': raw[index * 16:(index + 1) * 16].hex()}
                   for index in range(count)]
        if any(record['dispatch_kind'] not in (0, 1, 2) for record in records):
            raise ValueError('expression action program has an unsupported dispatch kind')
        if (struct.pack('>IB3s', pointer, count, reserved) != header
                or b''.join(bytes.fromhex(record['raw_bytes']) for record in records) != raw):
            raise ValueError('expression action program failed decoded-byte reconstruction')
        programs.append({'selector': selector, 'native_action': action,
                         'table_address': f'0x{address:08X}', 'table_bytes': header.hex(),
                         'program_address': f'0x{pointer:08X}', 'record_count': count,
                         'decoded_size': len(raw), 'sha1': hashlib.sha1(raw).hexdigest(),
                         'records': records})
    return programs


def encode_expression_presets(presets: list[dict]) -> bytes:
    records = []
    for index, preset in enumerate(presets):
        if preset['index'] != index or len(preset['blink_selector_bytes']) != 2 or len(preset['texture_descriptor_overrides']) != 2:
            raise ValueError('expression preset index or field extent changed')
        records.append(struct.pack('>6BH2B', *preset['blink_selector_bytes'], preset['morph_shape'],
            preset['morph_transition_duration'], preset['animation_selector'], preset['reserved_byte'],
            preset['animation_duration_raw'], *preset['texture_descriptor_overrides']))
    return b''.join(records)


def parse_expression_presets(data: bytes) -> list[dict]:
    layout = parse_defaults(data)
    size = layout['expression_size']
    if size % 10:
        raise ValueError('expression preset block is not a complete ten-byte record array')
    payload = data[layout['expression_offset']:layout['expression_offset'] + size]
    presets = []
    for index, values in enumerate(struct.iter_unpack('>6BH2B', payload)):
        left, right, shape, duration, animation, reserved, animation_duration, texture_left, texture_right = values
        presets.append({'index': index, 'blink_selector_bytes': [left, right],
                        'actor_blink_codes': [(left + 10) & 255, (right + 10) & 255],
                        'morph_shape': shape, 'morph_transition_duration': duration,
                        'animation_selector': animation, 'reserved_byte': reserved,
                        'animation_duration_raw': animation_duration,
                        'texture_descriptor_overrides': [texture_left, texture_right]})
    if encode_expression_presets(presets) != payload:
        raise ValueError('expression presets failed decoded-byte reconstruction')
    return presets
